# -*- coding: utf-8 -*-
"""Propzy (BS4)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ua3nn-Cq0F3igAMkdHVFJHtV33n3wBJo

# Libraries import
"""

!pip install beautifulsoup4

from bs4 import BeautifulSoup
import requests
from csv import writer
import pandas as pd

"""# Setting up"""

# PROPZY
page = 0
#while page < 2:
page = page + 1
url = 'https://propzy.vn/mua/bat-dong-san/hcm/p' + str(page)
page = requests.get(url)

print(page)

"""# Scraping"""

soup = BeautifulSoup(page.content, 'html.parser')

lists = soup.find_all('div', class_='bl-info-listing')

data = []



for info in lists:
  row = []
  # Title
  title = info.find(class_='p-info-listing').text
  
  # Location
  location = info.find(class_='p-location').find_all('a')
  address = ''
  for a in location:
    if a != location[-1]:
      address += a.text + ', '
    else:
      address += a.text + '.'

  # Facilities
  facilities = info.find('div', class_='bl-tilities')
  if facilities is not None:
    facilities = facilities.find_all('span')
  if facilities is not None:
    bed = facilities[0].text
    bath = facilities[1].text
    area = facilities[2].text.replace('m²', '').strip()
    compass = facilities[3].text

  # Price
  price = info.find(class_='h3-title-price')
  # Eliminate <span>
  if price.find('span') is not None:
    price.find('span').decompose()
  price = price.text.replace('tỷ', '').strip()

  # Putting into 2-D data frame:
  row = [title, price, location, bed, bath, area, compass]
  data.append(row)
  
df = pd.DataFrame(data, columns=['titles', 'prices', 'locations', 'beds', 'baths', 'areas' ,'compasses'])
df.head()